name: movie_review
version: 1.0.0+1
publish_to: none
description: A new movie review project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get_cli: ^1.8.1
  get: 4.6.5
  auto_size_text: ^3.0.0
  http: ^1.1.0
  flutter_easyloading: ^3.0.5
  flutter: 
    sdk: flutter
  flutter_html: ^3.0.0-beta.2

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/samples/


